//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSMacros
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrosoftCorporation.VSMacros.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tool window cannot be created..
        /// </summary>
        public static string CannotCreateWindow {
            get {
                return ResourceManager.GetString("CannotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; and all its contents will be sent to the recycle bin..
        /// </summary>
        public static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; will be sent to the recycle bin..
        /// </summary>
        public static string DeleteMacro {
            get {
                return ResourceManager.GetString("DeleteMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To.
        /// </summary>
        public static string DialogAssignTo {
            get {
                return ResourceManager.GetString("DialogAssignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve command index from selection..
        /// </summary>
        public static string DialogCannotRetrieveCommandIndex {
            get {
                return ResourceManager.GetString("DialogCannotRetrieveCommandIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign custom keyboard shortcut.
        /// </summary>
        public static string DialogCustomShortcut {
            get {
                return ResourceManager.GetString("DialogCustomShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DialogMacroName {
            get {
                return ResourceManager.GetString("DialogMacroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        public static string DialogPlayback {
            get {
                return ResourceManager.GetString("DialogPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut already used. Overwrite?.
        /// </summary>
        public static string DialogShortcutAlreadyUsed {
            get {
                return ResourceManager.GetString("DialogShortcutAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined Keyboard Shortcuts.
        /// </summary>
        public static string DialogShortcutSelectionText {
            get {
                return ResourceManager.GetString("DialogShortcutSelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times.
        /// </summary>
        public static string DialogTimesPlural {
            get {
                return ResourceManager.GetString("DialogTimesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string DialogTimesSingular {
            get {
                return ResourceManager.GetString("DialogTimesSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists. Do you want to overwrite it?.
        /// </summary>
        public static string DragDropFileExists {
            get {
                return ResourceManager.GetString("DragDropFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ExitCaption {
            get {
                return ResourceManager.GetString("ExitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording in process, are you sure to exit?.
        /// </summary>
        public static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FolderClosedIcon {
            get {
                object obj = ResourceManager.GetObject("FolderClosedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FolderOpenedIcon {
            get {
                object obj = ResourceManager.GetObject("FolderOpenedIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}.js&apos; error.
        /// </summary>
        public static string MacroFileError {
            get {
                return ResourceManager.GetString("MacroFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro not found on disk..
        /// </summary>
        public static string MacroNotFound {
            get {
                return ResourceManager.GetString("MacroNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the changes to {0} before executing it?.
        /// </summary>
        public static string MacroNotSavedBeforePlayback {
            get {
                return ResourceManager.GetString("MacroNotSavedBeforePlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        public static string MatchCase {
            get {
                return ResourceManager.GetString("MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start &amp;Recording.
        /// </summary>
        public static string MenuTextNormal {
            get {
                return ResourceManager.GetString("MenuTextNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop &amp;Recording.
        /// </summary>
        public static string MenuTextRecording {
            get {
                return ResourceManager.GetString("MenuTextRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RecordRound {
            get {
                object obj = ResourceManager.GetObject("RecordRound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RootIcon {
            get {
                object obj = ResourceManager.GetObject("RootIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not valid in this context.
        /// </summary>
        public static string ScriptErrorCommandNotValid {
            get {
                return ResourceManager.GetString("ScriptErrorCommandNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search within file contents.
        /// </summary>
        public static string SearchWithinFileContents {
            get {
                return ResourceManager.GetString("SearchWithinFileContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected shortcut is invalid..
        /// </summary>
        public static string ShortcutIsInvalid {
            get {
                return ResourceManager.GetString("ShortcutIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shortcuts have been modified. Do you want to save the changes?.
        /// </summary>
        public static string ShortcutsChanged {
            get {
                return ResourceManager.GetString("ShortcutsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts file was not found..
        /// </summary>
        public static string ShortcutsFileNotFound {
            get {
                return ResourceManager.GetString("ShortcutsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing....
        /// </summary>
        public static string StatusBarPlayingText {
            get {
                return ResourceManager.GetString("StatusBarPlayingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string StatusBarReadyText {
            get {
                return ResourceManager.GetString("StatusBarReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording....
        /// </summary>
        public static string StatusBarRecordingText {
            get {
                return ResourceManager.GetString("StatusBarRecordingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StopIcon {
            get {
                object obj = ResourceManager.GetObject("StopIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro Explorer.
        /// </summary>
        public static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
    }
}
